### ISSUE TITLE
Question: Is emulator safe for tft?

### ISSUE THREAD

**Issue by pxxzhe001** [TeamFightTacticsBots/Alune#9]
I have made my own clickbot before for token farming and after vanguard update I'm pretty sure it can detect background python executions and probably timed clicks and movements and movements. Thinking of moving to emulator but not sure if its safe. I've saw someone complaining getting banned for using bluestacks. If you have tested please let me know.

**Comment by akshualy** [comment]
From our initial tests it's safe. In fact, I've had the bot running for about a week straight without ever stopping it (since it now runs in the background), so if there was any detection, it sure would've triggered.

I saw the report about someone getting banned on BlueStacks as well, I have asked for screenshots/proof of this but haven't received any so far. It could be that there is a basic check for repeated clicks at the exact same pixel positions, but that'd just be a guess and nothing I can prove at the moment. We're using randomization for our clicks anyway.
